#!/bin/bash

echo "==============================================="
echo "  Switching to Node.js Server"
echo "==============================================="
echo ""
echo "This script will help you update your .replit configuration"
echo "to run the Node.js server instead of the Python Flask wrapper."
echo ""
echo "MANUAL STEPS REQUIRED:"
echo ""
echo "1. Open the .replit file in your editor"
echo ""
echo "2. Find this section:"
echo "   [[workflows.workflow.tasks]]"
echo "   task = \"shell.exec\""
echo "   args = \"gunicorn --bind 0.0.0.0:5000 --reuse-port --reload main:app\""
echo "   waitForPort = 5000"
echo ""
echo "3. Replace it with:"
echo "   [[workflows.workflow.tasks]]"
echo "   task = \"shell.exec\""
echo "   args = \"NODE_ENV=development node server/index.js\""
echo "   waitForPort = 5000"
echo ""
echo "4. Save the file and restart the workflow"
echo ""
echo "OR run the Node.js server directly with:"
echo "   NODE_ENV=development node server/index.js"
echo ""
echo "==============================================="
